project:
  type: website

website:
  title: "Leo Lai"
  navbar:
    background: "blue"
    left:
      - href: index.qmd
        text: Home
      - href: resume.pdf
        text: CVS
      - href: Assignments.qmd
        text: Assignments

format:
  html:
    toc: true
    toc-location: left
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    self-contained: true
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
execute: 
  freeze: auto

editor: visual

